40 hours is missing for all developers.
MKRNaqeebi/MKRNaqeebi pull request #1
Opened 2023-02-21 06:21 UTC by AliHanifdev1

2023-02-21 06:38 UTC, MKRNaqeebi requested changes
remove console.log
name function and variable properly

2023-02-21 17:50 UTC, MKRNaqeebi requested changes

2023-02-21 17:50 UTC, MKRNaqeebi commented on src/components/FortyHours.vue
> +    allI(repos) {
name this function properly

2023-02-21 17:50 UTC, MKRNaqeebi commented on src/components/FortyHours.vue
> +            //this.formate(response.data);
remove this unnecessary comment

2023-02-22 09:35 UTC, AliHanifdev1 commented on src/components/FortyHours.vue
> +            //this.formate(response.data);
done

2023-02-22 09:35 UTC, AliHanifdev1 commented on src/components/FortyHours.vue
> +    allI(repos) {
done

2023-02-22 10:17 UTC, MKRNaqeebi requested changes

2023-02-22 10:17 UTC, MKRNaqeebi commented on src/components/FortyHours.vue
> +    AllIssues(repos) {
make the camel case's 1st letter small.

2023-02-22 10:17 UTC, MKRNaqeebi commented on src/components/FortyHours.vue
> +            //console.log("res", response.data);
remove it

2023-02-22 10:31 UTC, AliHanifdev1 commented on src/components/FortyHours.vue
> +    AllIssues(repos) {
done

2023-02-22 10:31 UTC, AliHanifdev1 commented on src/components/FortyHours.vue
> +            //console.log("res", response.data);
done

2023-02-22 11:04 UTC, MKRNaqeebi approved these changes

2023-02-22 11:04 UTC, merged